# Generated by Django 4.1.2 on 2022-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slackUsername", models.CharField(max_length=200)),
                ("backend", models.BooleanField()),
                ("age", models.IntegerField(max_length=200)),
                ("bio", models.CharField(max_length=1000)),
            ],
        ),
    ]
